name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - bokeh=3.2.0
  - cartopy=0.21.1
  - dask=2023.7.0
  - geopandas
  - holoviews=1.16.2
  - hvplot=0.8.4
  - netcdf4=1.6.4
  - matplotlib=3.4.3
  - pip
  - pandas=2.0.3
  - pyproj=3.6.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - shapely=2.0.1
  - xarray=2023.7.0
  - zarr=2.15.0
  - python=3.9
  - bokeh=3.2.0
  - cartopy=0.21.1  
  - dask=2023.7.0
  - holoviews=1.16.2
  - hvplot=0.8.4
  - netcdf4=1.6.4
  - pip
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - shapely=2.0.1
  - tqdm=4.65.0
  - xarray=2023.7.0
  - zarr=2.15.0